name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Clean up previous builds
        run: |
          if [ -d "./bin" ]; then
            rm -rf ./bin
          fi

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v -o ./bin/myapp .

      - name: Run Tests
        run: go test -v ./...

  go-lint:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59